--- 
title: "Data Analytics One - Class Materials and Lessons"
author: "Authored and Edited by: Dr. Turner and Seth Cooper"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a book that contains all of the materials and lessons for Dr. Turner's data analytics one course."
---

# Introduction

This is a book written in [**Markdown**](https://vimeo.com/178485416) which contains all the materials and lessons for data analytics one. If you miss a day, want to review something we covered in class, or for any reason want to look for a worksheet, this is where you can go. 

Each chapter contains a different topic we will cover during the semester. Some larger topics are split into two chapters to make accessing the materials a little more intuitive. 

This book is updated automatically with any changes made to the documents during the semester, so if at any point you are told there was a change in the assignment, you can come here to get the updated version.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown','dplyr'
), 'packages.bib')
```

## About R

R is a software language for carrying out complicated (and simple) statistical analyses. It includes
routines for data summary and exploration, graphical presentation and data modelling. The aim of
this document is to provide you with a basic fluency in the language. It is suggested that you work
through this document at the computer, having started an R session. Type in all of the commands
that are printed, and check that you understand how they operate. Then try the simple exercises
at the end of each section.

When you work in R you create objects that are stored in the current workspace (sometimes
called image). Each object created remains in the image unless you explicitly delete it. At the end
of the session the workspace will be lost unless you save it. You can save the workspace at any
time by clicking on the disc icon at the top of the control panel.
Commands written in R are saved in memory throughout the session. You can scroll back to
previous commands typed by using the ‘up’ arrow key (and ‘down’ to scroll back again). You can
also ‘copy’ and ‘paste’ using standard windows editor techniques (for example, using the ‘copy’
and ‘paste’ dialog buttons). If at any point you want to save the transcript of your session, click
on ‘File’ and then ‘Save History’, which will enable you to save a copy of the commands you have
used for later use. As an alternative you might copy and paste commands manually into a notepad
editor or something similar.

## What Good is Data Science?

There are a variety of different applications for R. Yes, the more obvious ones would be things such as machine learning, artificial intelligence, and data mining. However, the possibilities with this program are honestly limitless. Take a look at this rather funny example of data analytics being used by retail giant Target to predict whether women were pregnant and how it put one teenager in a rather uncomfortable situation.

[Click for Target Pregnancy Model Story](https://www.forbes.com/sites/kashmirhill/2012/02/16/how-target-figured-out-a-teen-girl-was-pregnant-before-her-father-did/)

What other applications are there? Well, are you interested in sports? Did you know that almost all professional athletic teams have dedicated teams of data scientists whose job it is to watch for patterns and collect data from the games in order to help the coaches make better calls and more effective plays? 

[Click Data Analytics in the NBA Story](https://digital.hbs.edu/platform-digit/submission/how-data-analytics-is-revolutionizing-the-nba/)

Presbyterian College has a very high number of STEM majors. Specifically, biology is one of the most declared majors on campus. Data science is used by biologists and many other scientists around the world to help create data and compelling visualizations in order to convey their findings. Check out this interesting story about data science being used in the world of biology. 

[Click for Computational Biology Story](https://www.datasciencecentral.com/profiles/blogs/the-next-big-thing-in-data-science-is-biology)

As you can no doubt see, it is more than likely safe to say that data science will one day be a major factor in almost every field some day. Data already surrounds us and is used by companies all over the world for a variety of tasks. By creating a foundation of these skills for yourself, regardless of whether your job title contains the words "data science", you will be an asset to your company. Simply having the ability to understand and interpret data is one of the most sought after skills in the corporate sphere today. 