<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Linear Regression | Data Analytics One - Class Materials and Lessons</title>
  <meta name="description" content="This is a book that contains all of the materials and lessons for Dr. Turner’s data analytics one course." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Linear Regression | Data Analytics One - Class Materials and Lessons" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a book that contains all of the materials and lessons for Dr. Turner’s data analytics one course." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Linear Regression | Data Analytics One - Class Materials and Lessons" />
  
  <meta name="twitter:description" content="This is a book that contains all of the materials and lessons for Dr. Turner’s data analytics one course." />
  

<meta name="author" content="Authored and Edited by: Dr. Turner and Seth Cooper" />


<meta name="date" content="2021-11-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="gdh-ice-cream.html"/>
<link rel="next" href="logistic-regression.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Analytics One Bookdown</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about-r"><i class="fa fa-check"></i><b>1.1</b> About R</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#what-good-is-data-science"><i class="fa fa-check"></i><b>1.2</b> What Good is Data Science?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>2</b> R basics and workflows</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-basics.html"><a href="r-basics.html#basics-of-working-with-r-at-the-command-line-and-rstudio-goodies"><i class="fa fa-check"></i><b>2.1</b> Basics of working with R at the command line and RStudio goodies</a></li>
<li class="chapter" data-level="2.2" data-path="r-basics.html"><a href="r-basics.html#workspace-and-working-directory"><i class="fa fa-check"></i><b>2.2</b> Workspace and working directory</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="r-basics.html"><a href="r-basics.html#workspace-.rdata"><i class="fa fa-check"></i><b>2.2.1</b> Workspace, <code>.RData</code></a></li>
<li class="chapter" data-level="2.2.2" data-path="r-basics.html"><a href="r-basics.html#working-directory"><i class="fa fa-check"></i><b>2.2.2</b> Working directory</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="r-basics.html"><a href="r-basics.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html"><i class="fa fa-check"></i><b>3</b> R vs. Excel</a>
<ul>
<li class="chapter" data-level="3.1" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#both-are-useful"><i class="fa fa-check"></i><b>3.1</b> Both are useful</a></li>
<li class="chapter" data-level="3.2" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#differences-between-r-and-excel"><i class="fa fa-check"></i><b>3.2</b> Differences Between R and Excel</a></li>
<li class="chapter" data-level="3.3" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#ease-of-use-learning-the-software"><i class="fa fa-check"></i><b>3.3</b> Ease of Use &amp; Learning the Software</a></li>
<li class="chapter" data-level="3.4" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#replicating-analysis"><i class="fa fa-check"></i><b>3.4</b> Replicating Analysis</a></li>
<li class="chapter" data-level="3.5" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#visualization"><i class="fa fa-check"></i><b>3.5</b> Visualization</a></li>
<li class="chapter" data-level="3.6" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#packages"><i class="fa fa-check"></i><b>3.6</b> Packages</a></li>
<li class="chapter" data-level="3.7" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#careers"><i class="fa fa-check"></i><b>3.7</b> Careers</a></li>
<li class="chapter" data-level="3.8" data-path="r-vs.-excel.html"><a href="r-vs.-excel.html#summary-using-r-and-excel"><i class="fa fa-check"></i><b>3.8</b> Summary – Using R and Excel</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html"><i class="fa fa-check"></i><b>4</b> Objects and Arithmetic</a>
<ul>
<li class="chapter" data-level="4.1" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html#basic-functions"><i class="fa fa-check"></i><b>4.2</b> Basic Functions</a></li>
<li class="chapter" data-level="4.3" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html#statistics-and-summaries"><i class="fa fa-check"></i><b>4.3</b> Statistics and Summaries</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html#statistical-analysis"><i class="fa fa-check"></i><b>4.3.1</b> Statistical Analysis</a></li>
<li class="chapter" data-level="4.3.2" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html#anscombes-quartet"><i class="fa fa-check"></i><b>4.3.2</b> Anscombe’s Quartet</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="objects-and-arithmetic.html"><a href="objects-and-arithmetic.html#exercises-1"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="summaries-and-subscripting.html"><a href="summaries-and-subscripting.html"><i class="fa fa-check"></i><b>5</b> Summaries and Subscripting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="summaries-and-subscripting.html"><a href="summaries-and-subscripting.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="summaries-and-subscripting.html"><a href="summaries-and-subscripting.html#exercises-summaries-and-subscripting"><i class="fa fa-check"></i><b>5.2</b> Exercises (Summaries and Subscripting)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="matrices.html"><a href="matrices.html"><i class="fa fa-check"></i><b>6</b> Matrices</a>
<ul>
<li class="chapter" data-level="6.1" data-path="matrices.html"><a href="matrices.html#cbind-and-rbind"><i class="fa fa-check"></i><b>6.1</b> CBind and RBind</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="matrices.html"><a href="matrices.html#review-questions"><i class="fa fa-check"></i><b>6.1.1</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="matrices.html"><a href="matrices.html#matrix-function"><i class="fa fa-check"></i><b>6.2</b> Matrix Function</a></li>
<li class="chapter" data-level="6.3" data-path="matrices.html"><a href="matrices.html#exercises-2"><i class="fa fa-check"></i><b>6.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="playing-with-data-using-mtcars.html"><a href="playing-with-data-using-mtcars.html"><i class="fa fa-check"></i><b>7</b> Playing With Data (Using mtcars)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="playing-with-data-using-mtcars.html"><a href="playing-with-data-using-mtcars.html#practicing-with-mtcars-data-set"><i class="fa fa-check"></i><b>7.1</b> Practicing with <code>mtcars</code> data set</a></li>
<li class="chapter" data-level="7.2" data-path="playing-with-data-using-mtcars.html"><a href="playing-with-data-using-mtcars.html#excerises-for-you"><i class="fa fa-check"></i><b>7.2</b> Excerises for you:</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>8</b> DPLYR</a>
<ul>
<li class="chapter" data-level="8.1" data-path="dplyr.html"><a href="dplyr.html#introduction-3"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="dplyr.html"><a href="dplyr.html#single-table-verbs"><i class="fa fa-check"></i><b>8.2</b> Single table verbs</a></li>
<li class="chapter" data-level="8.3" data-path="dplyr.html"><a href="dplyr.html#the-pipe"><i class="fa fa-check"></i><b>8.3</b> The pipe</a></li>
<li class="chapter" data-level="8.4" data-path="dplyr.html"><a href="dplyr.html#loading-dplyr-and-the-nycflights13-dataset"><i class="fa fa-check"></i><b>8.4</b> Loading dplyr and the nycflights13 dataset</a></li>
<li class="chapter" data-level="8.5" data-path="dplyr.html"><a href="dplyr.html#choosing-columns-select-rename"><i class="fa fa-check"></i><b>8.5</b> Choosing columns: select, rename</a></li>
<li class="chapter" data-level="8.6" data-path="dplyr.html"><a href="dplyr.html#choosing-rows-filter-between-slice-sample_n-top_n-distinct"><i class="fa fa-check"></i><b>8.6</b> Choosing rows: filter, between, slice, sample_n, top_n, distinct</a></li>
<li class="chapter" data-level="8.7" data-path="dplyr.html"><a href="dplyr.html#adding-new-variables-mutate-transmute-add_rownames"><i class="fa fa-check"></i><b>8.7</b> Adding new variables: mutate, transmute, add_rownames</a></li>
<li class="chapter" data-level="8.8" data-path="dplyr.html"><a href="dplyr.html#grouping-and-counting-summarise-tally-count-group_size-n_groups-ungroup"><i class="fa fa-check"></i><b>8.8</b> Grouping and counting: summarise, tally, count, group_size, n_groups, ungroup</a></li>
<li class="chapter" data-level="8.9" data-path="dplyr.html"><a href="dplyr.html#creating-data-frames-data_frame"><i class="fa fa-check"></i><b>8.9</b> Creating data frames: data_frame</a></li>
<li class="chapter" data-level="8.10" data-path="dplyr.html"><a href="dplyr.html#joining-merging-tables-left_join-right_join-inner_join-full_join-semi_join-anti_join"><i class="fa fa-check"></i><b>8.10</b> Joining (merging) tables: left_join, right_join, inner_join, full_join, semi_join, anti_join</a></li>
<li class="chapter" data-level="8.11" data-path="dplyr.html"><a href="dplyr.html#viewing-more-output-print-view"><i class="fa fa-check"></i><b>8.11</b> Viewing more output: print, View</a></li>
<li class="chapter" data-level="8.12" data-path="dplyr.html"><a href="dplyr.html#resources"><i class="fa fa-check"></i><b>8.12</b> Resources</a></li>
<li class="chapter" data-level="8.13" data-path="dplyr.html"><a href="dplyr.html#data-school"><i class="fa fa-check"></i><b>8.13</b> Data School</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="more-dplyr.html"><a href="more-dplyr.html"><i class="fa fa-check"></i><b>9</b> More DPLYR</a>
<ul>
<li class="chapter" data-level="9.1" data-path="more-dplyr.html"><a href="more-dplyr.html#introduction-4"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="more-dplyr.html"><a href="more-dplyr.html#single-table-verbs-1"><i class="fa fa-check"></i><b>9.2</b> Single table verbs</a></li>
<li class="chapter" data-level="9.3" data-path="more-dplyr.html"><a href="more-dplyr.html#more-with-the-pipe"><i class="fa fa-check"></i><b>9.3</b> More with the pipe</a></li>
<li class="chapter" data-level="9.4" data-path="more-dplyr.html"><a href="more-dplyr.html#loading-dplyr-and-the-starwars-dataset"><i class="fa fa-check"></i><b>9.4</b> Loading <code>dplyr</code> and the <code>starwars</code> dataset</a></li>
<li class="chapter" data-level="9.5" data-path="more-dplyr.html"><a href="more-dplyr.html#starwars-excercises"><i class="fa fa-check"></i><b>9.5</b> <code>starwars</code> Excercises</a></li>
<li class="chapter" data-level="9.6" data-path="more-dplyr.html"><a href="more-dplyr.html#nycflights13-excercises"><i class="fa fa-check"></i><b>9.6</b> <code>nycflights13</code> Excercises</a></li>
<li class="chapter" data-level="9.7" data-path="more-dplyr.html"><a href="more-dplyr.html#storms-excercises"><i class="fa fa-check"></i><b>9.7</b> <code>storms</code> Excercises</a></li>
<li class="chapter" data-level="9.8" data-path="more-dplyr.html"><a href="more-dplyr.html#starwars-excercises-1"><i class="fa fa-check"></i><b>9.8</b> <code>starwars</code> Excercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="gdh-ice-cream.html"><a href="gdh-ice-cream.html"><i class="fa fa-check"></i><b>10</b> GDH Ice Cream</a>
<ul>
<li class="chapter" data-level="10.1" data-path="gdh-ice-cream.html"><a href="gdh-ice-cream.html#problem-introduction"><i class="fa fa-check"></i><b>10.1</b> Problem Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="gdh-ice-cream.html"><a href="gdh-ice-cream.html#assignment"><i class="fa fa-check"></i><b>10.2</b> Assignment</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>11</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="linear-regression.html"><a href="linear-regression.html#what-is-machine-learning"><i class="fa fa-check"></i><b>11.1</b> What is Machine Learning?</a></li>
<li class="chapter" data-level="11.2" data-path="linear-regression.html"><a href="linear-regression.html#model-structure"><i class="fa fa-check"></i><b>11.2</b> Model Structure</a></li>
<li class="chapter" data-level="11.3" data-path="linear-regression.html"><a href="linear-regression.html#interpretation-of-the-model"><i class="fa fa-check"></i><b>11.3</b> Interpretation of the Model</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="linear-regression.html"><a href="linear-regression.html#p-values"><i class="fa fa-check"></i><b>11.3.1</b> P-Values</a></li>
<li class="chapter" data-level="11.3.2" data-path="linear-regression.html"><a href="linear-regression.html#multiple-r-squared"><i class="fa fa-check"></i><b>11.3.2</b> Multiple R-Squared</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="linear-regression.html"><a href="linear-regression.html#applying-the-model-to-make-predictions"><i class="fa fa-check"></i><b>11.4</b> Applying the Model to Make Predictions</a></li>
<li class="chapter" data-level="11.5" data-path="linear-regression.html"><a href="linear-regression.html#review-questions-1"><i class="fa fa-check"></i><b>11.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#introduction-5"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#training-data-and-test-data"><i class="fa fa-check"></i><b>12.2</b> Training Data and Test Data</a></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#model-structure-1"><i class="fa fa-check"></i><b>12.3</b> Model Structure</a></li>
<li class="chapter" data-level="12.4" data-path="logistic-regression.html"><a href="logistic-regression.html#model-interpretation"><i class="fa fa-check"></i><b>12.4</b> Model Interpretation</a></li>
<li class="chapter" data-level="12.5" data-path="logistic-regression.html"><a href="logistic-regression.html#review-questions-2"><i class="fa fa-check"></i><b>12.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="dealing-with-errors.html"><a href="dealing-with-errors.html"><i class="fa fa-check"></i><b>13</b> Dealing with Errors</a>
<ul>
<li class="chapter" data-level="13.1" data-path="dealing-with-errors.html"><a href="dealing-with-errors.html#introduction-6"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="dealing-with-errors.html"><a href="dealing-with-errors.html#troubleshooting-typical-errors"><i class="fa fa-check"></i><b>13.2</b> Troubleshooting Typical Errors</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="data-analytics-i-quizzes.html"><a href="data-analytics-i-quizzes.html"><i class="fa fa-check"></i><b>14</b> Data Analytics I Quizzes</a>
<ul>
<li class="chapter" data-level="14.1" data-path="data-analytics-i-quizzes.html"><a href="data-analytics-i-quizzes.html#quiz-one-linear-regression"><i class="fa fa-check"></i><b>14.1</b> Quiz One (Linear Regression)</a></li>
<li class="chapter" data-level="14.2" data-path="data-analytics-i-quizzes.html"><a href="data-analytics-i-quizzes.html#quiz-two"><i class="fa fa-check"></i><b>14.2</b> Quiz Two</a></li>
<li class="chapter" data-level="14.3" data-path="data-analytics-i-quizzes.html"><a href="data-analytics-i-quizzes.html#quiz-three"><i class="fa fa-check"></i><b>14.3</b> Quiz Three</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="practice-final-exam.html"><a href="practice-final-exam.html"><i class="fa fa-check"></i><b>15</b> Practice Final Exam</a>
<ul>
<li class="chapter" data-level="15.1" data-path="practice-final-exam.html"><a href="practice-final-exam.html#meter-freestyle-olympic-winning-time-seconds"><i class="fa fa-check"></i><b>15.1</b> 100-Meter Freestyle Olympic Winning Time (seconds)</a></li>
<li class="chapter" data-level="15.2" data-path="practice-final-exam.html"><a href="practice-final-exam.html#starwars-fun"><i class="fa fa-check"></i><b>15.2</b> Starwars fun</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analytics One - Class Materials and Lessons</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression" class="section level1" number="11">
<h1><span class="header-section-number">Chapter 11</span> Linear Regression</h1>
<div id="what-is-machine-learning" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> What is Machine Learning?</h2>
<p>This is where the fun stuff begins! What we have learned up to this point has barely scratched the surface of what R is capable of. In the world of data science, R is used for three primary purposes, those purposes are (1) data transformation, (2) data wrangling, (3) machine learning. The other two purposes have been covered in earlier chapters of this book. The reason we covered the other topics first is that that lay the foundation. In the real world, it is likely you will never be given a clean data set, and you will have to do some wrangling and transformation before anything else is possible. After all, in the experience of many data science students, cleaning the data is the most tedious and time consuming process of a project.</p>
<p>Enough of the old stuff, what is machine learning? According to the Merriam-Webster Dictionary, machine learning is “the process by which a computer is able to improve its own performance by continuously incorporating new data into an existing statistical model.” Let’s take a trip back to the Target story discussed in the introductory chapter. The data scientist, or more likely data scientists (collaborative work is essential in this field), that worked on that model were likely experts in machine learning. They were able to train the computer to look through thousands (probably more) of customers’ data and the computer, based off the algorithms written by these “data nerds,” was able to predict whether a customer was pregnant! Think of other possible applications of this technology? We could predict how well a student will preform on an exam, the risk of someone suffering from a heart attack, or the likelihood that someone will default on a loan. Every field in existence today could find a way to implement machine learning to optimize their business.</p>
<p>There are two branches of machine learning, supervised and unsupervised. Both have their own unique uses, however in this course we will focus on supervised machine learning. Supervised machine learning required us to provide a clean data set with clearly defined variables and instructions. Essentially, we give the computer the information it needs and provide it with specific instructions detailing what we would like to see happen, and it does the rest. Linear regression is typically the first method of supervised learning people are introduced to, and it will be the focus of this chapter.</p>
<p>Note, these concepts are not all common sense and can be difficult to wrap your head around at times. Be sure to constantly turn to your instructor or peers for assistance and remember that there are hundreds of online resources at your disposal. As with anything though, practice makes perfect. The popular rule states that mastering a skill can take upwards of 10,000 hours! Now, this course is not going to take you 10 years to complete, however the goal is that by the end of this chapter you will know your way around the basics of linear regression.</p>
</div>
<div id="model-structure" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> Model Structure</h2>
<p>Let’s look at a very simple model first. For this example, we will need to import the Introduction to Statistical Learning package (ISLR). We will use the “credit” data set that is part of the ISLR package.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="linear-regression.html#cb247-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb247-2"><a href="linear-regression.html#cb247-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;Credit&quot;</span>)</span>
<span id="cb247-3"><a href="linear-regression.html#cb247-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Credit)</span>
<span id="cb247-4"><a href="linear-regression.html#cb247-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb247-5"><a href="linear-regression.html#cb247-5" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> Limit <span class="sc">+</span> Ethnicity)</span></code></pre></div>
<p>lm is the function we use to create linear regression models. Now, before we discuss interpreting the results we get from this function, we will discuss the different parts of the model. The “~” symbol is the key to this entire equation. We are telling R to predict whatever is on the left side of the tilde using the variables on the right.</p>
</div>
<div id="interpretation-of-the-model" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Interpretation of the Model</h2>
<p>Let’s run a summary on this model and see what we get.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="linear-regression.html#cb248-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Balance ~ Limit + Ethnicity)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -677.39 -145.75   -8.75  139.56  776.46 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        -3.078e+02  3.417e+01  -9.007   &lt;2e-16 ***
## Limit               1.718e-01  5.079e-03  33.831   &lt;2e-16 ***
## EthnicityAsian      2.835e+01  3.304e+01   0.858    0.391    
## EthnicityCaucasian  1.381e+01  2.878e+01   0.480    0.632    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 234 on 396 degrees of freedom
## Multiple R-squared:  0.743,  Adjusted R-squared:  0.7411 
## F-statistic: 381.6 on 3 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>There is a lot of statistical jargon included in our summary that may be unfamiliar to those who have not taken statistics before. That is okay, however, because we are going to breakdown the main statistics we are interested in. Let’s start with our variables and their significance in the model.</p>
<div id="p-values" class="section level3" number="11.3.1">
<h3><span class="header-section-number">11.3.1</span> P-Values</h3>
<p>The p-value of our model helps us either prove or disprove the null-hypothesis of our test. In the case of this class, the null-hypothesis is that there is no relationship between the variables we are using to make the predictions and the actual variable we are predicting. In other words, the smaller our p-value the higher the level of significance there is between our variables. When we run a summary of our linear regression model we are give multiple p-values.</p>
<p>First, under coefficients, they are listed for each variable. This can help us optimize our model because we can see what variables are helping make the model more accurate versus those that may be hindering its performance. Also notice the asterisks next to our p-values. R kindly puts up to three stars next to each variable to help us visually tell if they are significant, essentially more stars means a lower p-value and thus a higher correlation.
The second place we see a p-value is at the bottom of our summary. This p-value will give us the overall correlation that exists in our model. As we see in this case, our p-values for this model is &lt; .00000000000000022, that is a tiny number and frankly a great p-value. Typically we want our p-value to be .05 or smaller. A p-value of .05 tells us that we have a confidence level of 95%.</p>
</div>
<div id="multiple-r-squared" class="section level3" number="11.3.2">
<h3><span class="header-section-number">11.3.2</span> Multiple R-Squared</h3>
<p>R-squared tells us how well our model explains the variance in our variable. In other words, is the reason for the change in the independent variable actually due to our model’s prediction? The higher the r-squared, the more accurate our model is because the better the data fits it. The maximum value r-squared can be is 1.</p>
<p>In our model’s case, we have a multiple r-squared of .743, this means our model is approximately 74.3% accurate as this is the amount of variance in the data caused by our dependent variable. Our r-squared could certainly be better. In fact, in the real world you typically are aiming for an r-squared above .9 or .95, which means you would have 90%-95% accuracy.</p>
</div>
</div>
<div id="applying-the-model-to-make-predictions" class="section level2" number="11.4">
<h2><span class="header-section-number">11.4</span> Applying the Model to Make Predictions</h2>
<p>This type of regression is refereed to as linear for a reason. If we were to visualize our model on a quadratic plane, we would see a line of best fit that would travel along through our data. This means we can simplify the model to fit the slope-intercept equation:</p>
<p>y = m(x)+b</p>
<p>In our case the slope of our line is related to the independent variables. The sum of these slopes will give us the overall slope of our line and the intercept is provided by the equation summary. If we modify this equation to be more applicable to our situation we would get something like this:</p>
<p>y = m<sub>1</sub>x<sub>1</sub> + m<sub>2</sub>x<sub>2</sub> … + b</p>
<p>Let’s look back at our example model from before</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="linear-regression.html#cb250-1" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> Limit <span class="sc">+</span> Ethnicity)</span>
<span id="cb250-2"><a href="linear-regression.html#cb250-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Balance ~ Limit + Ethnicity)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -677.39 -145.75   -8.75  139.56  776.46 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        -3.078e+02  3.417e+01  -9.007   &lt;2e-16 ***
## Limit               1.718e-01  5.079e-03  33.831   &lt;2e-16 ***
## EthnicityAsian      2.835e+01  3.304e+01   0.858    0.391    
## EthnicityCaucasian  1.381e+01  2.878e+01   0.480    0.632    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 234 on 396 degrees of freedom
## Multiple R-squared:  0.743,  Adjusted R-squared:  0.7411 
## F-statistic: 381.6 on 3 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We see that our limit variable has an estimate of 1.718e-01, this is our slope. When dealing with quantitative variables, we simply multiply our slope by the intended independent variable. So, if we wanted to find the balance of someone with a limit of 400, we would multiply 1.718e-01 by 400.</p>
<p>With the qualitative variables, in this case ethnicity, we multiply the estimate of the TRUE values by 1 and FALSE values by 0, thus cancelling the FALSE values out.</p>
<p>Let’s look at an example. If we used our above equation to predict the balance of someone who was Caucasian and has a credit limit of 500, here is the equation we would set up:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="linear-regression.html#cb252-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> (<span class="fl">1.718e-1</span><span class="sc">*</span><span class="dv">500</span>) <span class="sc">+</span> (<span class="fl">1.381e+01</span><span class="sc">*</span><span class="dv">1</span>) <span class="sc">+</span> (<span class="fl">2.835e+01</span><span class="sc">*</span><span class="dv">0</span>) <span class="sc">+</span> (<span class="sc">-</span><span class="fl">3.078e+02</span>)</span>
<span id="cb252-2"><a href="linear-regression.html#cb252-2" aria-hidden="true" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1] -208.09</code></pre>
<p>So, according to our model our customer would have a balance of -208.09. This number may seem funny, but keep in mind that our r-squared was not the best for this model making it inaccurate and the ethnicity of the customer was not highly correlated with the balance. Both of these facts may cause our prediction to be off. If we were actually creating a model that could predict balance, we would want to look at some of the more correlated variables in the data set.</p>
</div>
<div id="review-questions-1" class="section level2" number="11.5">
<h2><span class="header-section-number">11.5</span> Review Questions</h2>
<ol style="list-style-type: decimal">
<li><p>Create a linear model predicting using the ISLR data set that predicts a customer’s credit limit based on their age, current balance, and the number of cards they have.</p></li>
<li><p>What is the p-value of this model? What does this tell us?</p></li>
<li><p>List the variables in order from most correlated to least. How do you know that they are correlated?</p></li>
<li><p>What is the multiple r-squared of the model? What does this tell us? Is this good or bad?</p></li>
<li><p>What would be the credit limit of a 29 year old with 5 cards and a total balance of 1500?</p></li>
<li><p>Explain what the following piece of code does</p></li>
</ol>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="linear-regression.html#cb254-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb254-2"><a href="linear-regression.html#cb254-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;Credit&quot;</span>)</span>
<span id="cb254-3"><a href="linear-regression.html#cb254-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Credit)</span>
<span id="cb254-4"><a href="linear-regression.html#cb254-4" aria-hidden="true" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cards <span class="sc">~</span> Limit <span class="sc">+</span> Balance <span class="sc">+</span> Education)</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="gdh-ice-cream.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Data Analytics I Bookdown.pdf", "Data Analytics I Bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
